import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Box, Theme } from "@radix-ui/themes";
import TopNav from "@/components/ui/nav/top-nav.component";
import Footer from "@/components/ui/footer";

const merriweather = Outfit({
  subsets: ["latin"],
  variable: "--font-merriweather",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={merriweather.variable}>
        <Theme accentColor="tomato" appearance="dark">
          <Box className="relative overflow-hidden">
            <TopNav />
            {children}
            <Footer />
          </Box>
        </Theme>
      </body>
    </html>
  );
}
